<?php

namespace App\Enum;

enum EfectivoFpsEnum: string
{
    case QUADRO_PERMANENTE =  'QUADRO PERMANENTE';
    case SERVICO_MILITAR_DE_CONTARTO  = 'SERVICO MILITAR DE CONTARTO (QUADRO MILICIANO)';
    case SERVICO_MILITAR_OBRIGATORIO = 'SERVIÇO MILITAR OBRIGATORIO';
    case TRABALHADORES_CIVIS =  'TRABALHADORES CIVIS';
}
